name: Build PDF with LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'thesis/**'
  pull_request:
    paths:
      - 'thesis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Pull Docker image
        run: docker pull texlive/texlive:latest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run LaTeX Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace texlive/texlive:latest \
          /bin/bash -c "cd thesis && latexmk -pdf"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: thesis/thesis.pdf