name: Build PDF with LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'thesis/**'
  pull_request:
    paths:
      - 'thesis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Docker Layer Caching (DLC)
        run: |
          docker pull texlive/texlive:latest

      - name: Run LaTeX Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace texlive/texlive:latest \
          /bin/bash -c "cd thesis && latexmk -pdf"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: thesis/thesis.pdf